### ISSUE TITLE
Cant Update to v1.4.3

### ISSUE THREAD

**Issue by Jejid** [therealshabi/AutoImageFlipper#12]
I get an error: Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class technolifestyle.com.imageslider.FlipperLayout when i use v1.4.3 or 1.4.2 but if i use implementation 'com.github.therealshabi:AutoImageFlipper:v1.4.1' it work but flipper.setScrollTimeInSec(5); doesnt. 

Any idea how i can update to 1.4.3? Sorry for bothering but ur proyect is vital in my first app (http://bit.ly/domiyiacacias) MANY THANKS FOR IT

next my app graddle file:
[app gradle.txt](https://github.com/therealshabi/AutoImageFlipper/files/2715714/app.gradle.txt)

**Comment by therealshabi** [comment]
I'll check this asap

**Comment by therealshabi** [comment]
Resolved

**Comment by Jejid** [comment]
Many Thanks but still i have the trouble, i dont know what i am doing wrong Y_Y. I used 1.5.5 and 1.5.6 but same result

Here exactly error:

2019-01-08 21:11:57.747 1986-1986/domicilios.jejid.domiciliosllanos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: domicilios.jejid.domiciliosllanos, PID: 1986
    java.lang.RuntimeException: Unable to start activity ComponentInfo{domicilios.jejid.domiciliosllanos/domicilios.jejid.domiciliosllanos.MainActivity}: android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class technolifestyle.com.imageslider.FlipperLayout

**Comment by shahbaz-smpx** [comment]
Can you please send me the whole logcat error output? Actually the error is due to something else I presume

**Comment by shahbaz-smpx** [comment]
Also for once try using the jcenter method too

**Comment by therealshabi** [comment]
Can you please send me the whole logcat error output? Actually the error is due to something else I presume

**Comment by therealshabi** [comment]
Also for once try using the jcenter method too

**Comment by therealshabi** [comment]
@Jejid Can you give me link to your project if it's on Github?

**Comment by Jejid** [comment]
> @Jejid Can you give me link to your project if it's on Github?

After learning to upload a project in github xD i hope i did it well. Here is: https://github.com/Jejid/localappac

AutoImageFlipper is used in fragment_main.xml, activity_busqueda.xml, MainFragment.java (method: setLayoutFlipper), BusquedaActivity (method: setLayoutFlipperOne)
there i cant use flipper.setScrollTimeInSec (5); method nor remove bottom shadow

Many many thanks for your help and support

**Comment by therealshabi** [comment]
@Jejid I checked your code, actually, the thing is that you need to update certain things in your app.
Actually the problem is due to the fact that my library is for AndroidX projects, that is nothing but a better version of support libraries that you are currently using, support libraries would be deprecated after this curent version, so it's a good choice to already update your app. For that, first of all in your app's build.gradle update your targetSkVersion as well as compileSdkVersion along with buildToolsVersion to these values 
```groovy
android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "domicilios.jejid.domiciliosllanos"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 23
        versionName "1.2.3"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```
After syncing the changes go to Refactor (from the Android Studio's top bar) -> Migrate to AndroidX ,
after that it'll ask to save your existing project in the form of a zip file, do that and then refactor your code (which Android Studio will do automatically, atleast most part of it), then build and run your app in your device/emulator and voila it'll work perfectly then.

This is your final app level build.gradle 
```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    buildToolsVersion "28.0.3"
    defaultConfig {
        applicationId "domicilios.jejid.domiciliosllanos"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 23
        versionName "1.2.3"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.google.android.gms:play-services-maps:16.0.0'
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.1', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    implementation("com.github.bumptech.glide:glide:4.8.0@aar") {
        exclude group: "com.android.support"
        transitive = true
    }

    implementation 'androidx.recyclerview:recyclerview:1.1.0-alpha01'
    implementation 'androidx.appcompat:appcompat:1.1.0-alpha01'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha3'
    implementation 'com.google.android.material:material:1.1.0-alpha02'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.github.chrisbanes:PhotoView:2.1.3'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.1.0-alpha01'
    implementation 'org.jsoup:jsoup:1.8.3'
    testImplementation 'junit:junit:4.12'
    implementation 'com.sun.mail:android-mail:1.5.5'
    implementation 'com.sun.mail:android-activation:1.5.5'
    implementation 'com.github.therealshabi:AutoImageFlipper:1.5.6'
    implementation 'com.github.MikeOrtiz:TouchImageView:1.4.0'
}
```
This will be your gradle.properties file
```
# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx1536m

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
```
I have given this file for reference, you don't have to copy either of them, just do the steps as mentioned by me above.

**Comment by Jejid** [comment]
OMG many thanks for wonderfully support, I already did what u said me, and now it perfectly works¡. timescrool fixed and bottom shadow able to remove.. (Y) Thanks again
