### ISSUE TITLE
Issue with Kotlin

### ISSUE THREAD

**Issue by djsreeraj** [therealshabi/AutoImageFlipper#14]
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class technolifestyle.com.imageslider.CircularFlipperHandler, unresolved supertypes: androidx.viewpager.widget.ViewPager.OnPageChangeListener

![kotlin](https://user-images.githubusercontent.com/6124324/51273138-ff25f080-19f1-11e9-9560-6f1cd5cbe75c.PNG)

**Comment by therealshabi** [comment]
What version are you using?

**Comment by therealshabi** [comment]
Due to no response for 22 days, I am closing this issue. Please reopen if you're still facing any problem

**Comment by sedestrian** [comment]
I'm facing this problem

**Comment by sedestrian** [comment]
I'm using 1.5.6 and have tried also 1.5.7-beta, i'm not using androidx, that might be the problem, but i can't refactor the project to androidx
