### ISSUE TITLE
Background color of DOT

### ISSUE THREAD

**Issue by edgarscr** [therealshabi/AutoImageFlipper#27]
hi howdy? i need to change customize style of DOT because appear so bad 

![image](https://user-images.githubusercontent.com/33737821/67818565-b1a9da00-fa7f-11e9-8ccc-bf0bf30a0693.png)

**Comment by therealshabi** [comment]
Hey @edgarscr , sure I'll make it customisable as soon as possible.
Also, you can entirely remove the pager indicator if you want, by merely calling `flipperLayout.removeCircleIndicator();`.
Anyways, thanks for reporting this issue, I'll look Into this.

**Comment by therealshabi** [comment]
@edgarscr You cannot really customise the color of the dot as per this moment but there's many things that you can do here. First of all update your AutoImageFlipper to the latest released version by adding this line in your app level build.gradle file 
`implementation 'com.github.technolifestyle:AutoImageFlipper:1.6.0'`

Post that:
- You can change the background of the circular indicator by calling the function
`flipperLayout.setIndicatorBackgroundColor(<any_color_of_your_choice>)`,
- can set the background drawable of the circular indicator using
`flipperLayout.setIndicatorBackground(R.drawable.your_image)
- can hide the circular indicator and set your own indicator
```kotlin
    flipperLayout.removeCircleIndicator()
    flipperLayout.customizeFlipperPager { flipperPager ->
               // attach your custom indicator (with custom colours and features as you like) with flipper pager here
    }
```

**Comment by therealshabi** [comment]
Please do tell me if this solves your issue. You can have a look at our Readme and latest Release changelog at https://github.com/therealshabi/AutoImageFlipper/blob/master/README.md and https://github.com/therealshabi/AutoImageFlipper/releases/tag/v1.6.0 respectively
