### ISSUE TITLE
Flipper doesn't clear previous views when used inside a recyclerView

### ISSUE THREAD

**Issue by Tsabary** [therealshabi/AutoImageFlipper#28]
I've implemented FlipperLayout in part of a layout of items presented in a recyclerView. My problem is that the flipper shows images of other items. I've tried using `removeAllViewsInLayout()` when binding, and before adding the new views, but now the flipper just remains empty. I've also tried to use `clearDisappearingChildren()` which didnt help either. Any tips on how to use inside a recyclerview?

**Comment by therealshabi** [comment]
@Tsabary I request you please update your library to our latest v1.6.0 by adding 
`implementation 'com.github.technolifestyle:AutoImageFlipper:1.6.0'` in your app level build.gradle file. Post that you can refer to this section for your issue https://github.com/therealshabi/AutoImageFlipper#usage-with-the-recyclerview
If you have any other issues, please do tell me

**Comment by therealshabi** [comment]
Since there was no further activity on this issue, I've closed this.
