### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Blado** [therealshabi/AutoImageFlipper#36]
**Query**
Hey, would you Like to write me an example about how to use this autoimageslider? Im new to Java and dont understand Unit class , i used viewflipper Ver. 1.4.1 and it lags to much in scroll , wanna Try ver1.6.0. please
 
**Version of the library used**
Add the library version which is causing the bug

**Comment by therealshabi** [comment]
Hey @Blado, I'm so sorry you had to face lag while scrolling in v1.4.1.

Regarding the example, I've given one example as to how to use the library in the [Readme](https://github.com/therealshabi/AutoImageFlipper/blob/master/README.md) file. Please tell me if you don't understand something then and there. Also, please do tell me if you face any further issue in the Library

**Comment by Blado** [comment]
Its OK already, i tryed to Code by myself , after 30 min i had it.
