### ISSUE TITLE
 Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull

### ISSUE THREAD

**Issue by ramya2344** [therealshabi/AutoImageFlipper#41]
Getting this issue when i have used in Fragment - java

java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter context
        at technolifestyle.com.imageslider.FlipperView.<init>(Unknown Source:2)

**Comment by therealshabi** [comment]
Hey @ramya2344 

Probably the `context` you're passing in `FlipperView` is null, that's why this error is thrown.
Can you please ensure that the context for your FlipperView is non null?

**Comment by ramya2344** [comment]
Hi **therealshabi** ,
I have checked again. It's working.
Thank you.
