### ISSUE TITLE
setScrollTimeInSec not works

### ISSUE THREAD

**Issue by omar201816** [therealshabi/AutoImageFlipper#7]
Hi, I read the documentation for change the delay between images, but not works.

Im using, for delay 1 minute: flipper.setScrollTimeInSec(60)

But only delays 3 seconds, you know if im doing bad the things?

**Comment by therealshabi** [comment]
Hey thank you for bringing this to my attention, this is indeed a bug. I'll try to fix it asap, thanks

**Comment by therealshabi** [comment]
Fixed
