### ISSUE TITLE
How to remove bottom shadow in the layout?

### ISSUE THREAD

**Issue by Jejid** [therealshabi/AutoImageFlipper#8]
Hi, many thanks for thisone. Im new as developer and new here (github) too. I just want to know how to remover that bottom shadow in the layout maked for text visibilty. Thanks again

**Comment by therealshabi** [comment]
Shadow as in? You want to remove the blackish tint from the bottom text?

**Comment by Jejid** [comment]
Yes sir, that blackish tint for whites points and text. i dont need text rigth now and for better performance with backgorund is better without tint

**Comment by therealshabi** [comment]
Would you like to fix that? or should I do that?

**Comment by Jejid** [comment]
If you want or maybe I can learn to work with GitHub and understand the AutoImageFlipper code to improve it. I will continue paying attention to this. thanks again

**Comment by shahbaz-smpx** [comment]
That's great, I'll add this feature myself as of now, you may have a look at the changes that I'll make

**Comment by therealshabi** [comment]
That's great, I'll add this feature myself as of now, you may have a look at the changes that I'll make

**Comment by therealshabi** [comment]
Done.
Go through the Readme.md once to get all the functionalities of the library

**Comment by Jejid** [comment]
Many thanks therealshabi
